name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses + install SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Lock repos to mavenCentral + google across all modules
      - name: Add Gradle init script (lock repos)
        run: |
          cat > init-ci.gradle <<'EOF'
          allprojects { repositories { mavenCentral(); google() } }
          EOF

      # ---- Build using a provisioned Gradle (no wrapper needed) ----
      - name: Build Debug & Release (provisioned Gradle, retry 3x)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.4'
          arguments: >-
            -I init-ci.gradle
            --no-daemon
            --stacktrace
            --info
            assembleDebug
            assembleRelease

      - name: List build outputs
        run: |
          echo "=== APK outputs ==="
          ls -R app/build/outputs/apk || true
          echo "=== Bundle outputs ==="
          ls -R app/build/outputs/bundle || true

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: AiCam-APKs
          path: app/build/outputs/apk/**/*.apk
          if-no-files-found: warn

      - name: Upload AABs
        uses: actions/upload-artifact@v4
        with:
          name: AiCam-Bundles
          path: app/build/outputs/bundle/**/*.aab
          if-no-files-found: warn

      # ---- OPTIONAL: generate the Gradle Wrapper so you can commit it later ----
      - name: Generate Gradle Wrapper (8.4)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.4'
          arguments: wrapper --gradle-version 8.4

      - name: Upload wrapper files
        uses: actions/upload-artifact@v4
        with:
          name: Gradle-Wrapper-8.4
          path: |
            gradlew
            gradlew.bat
            gradle/wrapper/gradle-wrapper.jar
            gradle/wrapper/gradle-wrapper.properties
          if-no-files-found: warn
