name: Build APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Force all projects to use mavenCentral + google, in case any module adds others.
      - name: Add Gradle init script (lock repos)
        run: |
          cat > init-ci.gradle <<'EOF'
          allprojects {
            repositories {
              mavenCentral()
              google()
            }
          }
          EOF

      # Retry Gradle up to 3 times to ride out transient CDN hiccups
      - name: Build Debug APK (with retry)
        run: |
          set -e
          for i in 1 2 3; do
            echo "Attempt $i..."
            ./gradlew -I init-ci.gradle --no-daemon --stacktrace --info assembleDebug && break || {
              echo "Gradle failed on attempt $i, sleeping then retrying..."
              sleep 20
            }
          done
        shell: bash

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AiCam-debug-apk
          path: app/build/outputs/apk/debug/*.apk
